# Directories to ignore across multiple languages
IGNORED_DIRS = {
    ".git",
    ".svn",
    ".hg",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "bower_components",
    ".npm",
    ".yarn",
    "target",
    "build",
    ".gradle",
    "bin",
    "obj",
    ".idea",
    ".vscode",
    "vendor",
    "debug",
    "release",
    "dist",
    "out",
    "coverage",
    ".next",
    ".nuxt",
}

# Files to ignore (lock files, system files)
IGNORED_FILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "poetry.lock",
    "Pipfile.lock",
    "uv.lock",
    "Cargo.lock",
    "go.sum",
    ".DS_Store",
    "Thumbs.db",
    ".gitignore",
    ".gitattributes",
    ".dockerignore",
}

# Extensions considered binary (unreadable by LLM)
BINARY_EXTENSIONS = {
    ".pyc",
    ".pyo",
    ".pyd",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".svg",
    ".webp",
    ".zip",
    ".tar",
    ".gz",
    ".7z",
    ".rar",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".db",
    ".sqlite",
    ".class",
    ".jar",
    ".war",
}
