from typing import TypedDict, List


class AgentState(TypedDict):
    """
    Represents the state of the AI Test Agent workflow.

    Attributes:
        target_dir (str): The root directory of the project to test.
        file_list (List[str]): List of relevant file paths found in the project.
        project_context (str): Accumulated analysis of the codebase (signatures, docstrings).
        test_plan (str): The strategy for testing generated by the planner.
        generated_test_code (str): The actual code for the tests (e.g., Python, JS).
        test_results (str): Raw output from the test runner (stdout/stderr).
        final_report (str): A human-readable summary of the test execution.
    """

    target_dir: str
    file_list: List[str]
    project_context: str
    test_plan: str
    generated_test_code: str
    test_results: str
    final_report: str
